// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQycKfEAlt1W7ugeMCEaTYy8WDmZApyuk',
    appId: '1:30841547391:web:4b0d5c7e91a6c34f962d4a',
    messagingSenderId: '30841547391',
    projectId: 'sif-mobile-app-acb8b',
    authDomain: 'sif-mobile-app-acb8b.firebaseapp.com',
    storageBucket: 'sif-mobile-app-acb8b.firebasestorage.app',
    measurementId: 'G-3ZB5EL86HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAHk_J3-xUVy0vFrgXv1gqvaQaU82umyE',
    appId: '1:30841547391:android:4e18b8cd7711d6e5962d4a',
    messagingSenderId: '30841547391',
    projectId: 'sif-mobile-app-acb8b',
    storageBucket: 'sif-mobile-app-acb8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RjN1hPYpERsbaNS5tKURnq8tbpnMgWk',
    appId: '1:30841547391:ios:b4174c5d883ffe56962d4a',
    messagingSenderId: '30841547391',
    projectId: 'sif-mobile-app-acb8b',
    storageBucket: 'sif-mobile-app-acb8b.firebasestorage.app',
    iosBundleId: 'com.example.tut4u',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RjN1hPYpERsbaNS5tKURnq8tbpnMgWk',
    appId: '1:30841547391:ios:b4174c5d883ffe56962d4a',
    messagingSenderId: '30841547391',
    projectId: 'sif-mobile-app-acb8b',
    storageBucket: 'sif-mobile-app-acb8b.firebasestorage.app',
    iosBundleId: 'com.example.tut4u',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIi4n0WjAbuOj5LV_c0ptFJc4Tyge-1AU',
    appId: '1:30841547391:web:2e7fa00a64e115f2962d4a',
    messagingSenderId: '30841547391',
    projectId: 'sif-mobile-app-acb8b',
    authDomain: 'sif-mobile-app-acb8b.firebaseapp.com',
    storageBucket: 'sif-mobile-app-acb8b.firebasestorage.app',
    measurementId: 'G-796YM1Q8ZM',
  );
}
